# Generated by Django 6.0.6 on 2026-06-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('resource_type', models.CharField(choices=[('APP', 'Application'), ('DB', 'Database')], max_length=10)),
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('UAT', 'UAT'), ('DEV', 'Development')], default='PROD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
