# Generated by Django 6.0.6 on 2026-06-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('APP', 'Application'), ('DB', 'Database')], max_length=10)),
                ('unit', models.CharField(max_length=20)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('GREEN', 'GREEN'), ('AMBER', 'AMBER'), ('RED', 'RED')], max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metricdefinition')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource', 'metric', '-timestamp'], name='metrics_met_resourc_e8268f_idx'), models.Index(fields=['timestamp'], name='metrics_met_timesta_4d46c3_idx')],
            },
        ),
    ]
